- name: Run {{ container_name }} container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    image: "{{ image_name }}"
    detach: true
    tty: true
    restart_policy: always
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    security_opts: 
      - "label:disabled"
    volumes:
     - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
     - /var/run/docker.sock:/var/run/docker.sock:ro
    env: 
      WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock